name = "WAVIConstructor"
uuid = "4e0ae7ac-a5f3-419a-825d-d47dd6bf0df5"
authors = ["Thomas Zwagerman <thozwa@bas.ac.uk>"]
version = "0.1.0"

[deps]
ArchGDAL = "c9ce4bd3-c3d5-55b8-8973-c0e20141b8c3"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
WAVI = "881191c6-26ca-4787-919d-8f98f1c41532"

[sources]
WAVI = {url = "https://github.com/WAVI-ice-sheet-model/WAVI.jl.git", rev = "main"}

[compat]
ArchGDAL = "0.10.10"
DelimitedFiles = "1.9.1"
Interpolations = "0.16.2"
MAT = "0.11.4"
NCDatasets = "0.14.8"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "31c24e10-a181-5473-b8eb-7969acd0382f"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["LiveServer", "Revise"]
test = ["Test"]
